name: Events Demo 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#       - name: Output event data
#         run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: cache dependacy
        uses: actions/cache@v3.2.6
        with:
         path: ~/.npm
         key: nodemodule-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
